### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by lemonyte**

### CODE REVIEW

**Review by jnsougata — COMMENTED** [review]
image
As there's no custom erros to let the user know if the operation is successful or not they can just resort to http status code.. so return should stay there imo

**Comment by lemonyte** [comment]
Since the return type was already `-> None` I assumed they shouldn't return anything.

**Comment by jnsougata** [comment]
> Since the return type was already `-> None` I assumed they shouldn't return anything.

LOL ... didn't see that mb

**Review by jnsougata — COMMENTED** [review]
It's serving some static html so for serverless it's redundant to make it async as it won't serve any purpose

**Comment by lemonyte** [comment]
image

The type checker complains.

**Comment by jnsougata** [comment]
> image
> 
> The type checker complains.

👀  `# noqa`

**Pull request merged**
